const words = [
    "africa",
    "agent",
    "air",
    "alien",
    "amazon",
    "angel",
    "antarctica",
    "apple",
    "arm",
    "back",
    "band",
    "bank",
    "bark",
    "beach",
    "belt",
    "berlin",
    "berry",
    "board",
    "bond",
    "boom",
    "bow",
    "box",
    "bug",
    "canada",
    "capital",
    "cell",
    "center",
    "china",
    "chocolate",
    "circle",
    "club",
    "compound",
    "copper",
    "crash",
    "cricket",
    "cross",
    "death",
    "dice",
    "dinosaur",
    "doctor",
    "dog",
    "dress",
    "dwarf",
    "eagle",
    "egypt",
    "engine",
    "england",
    "europe",
    "eye",
    "fair",
    "fall",
    "fan",
    "field",
    "file",
    "film",
    "fish",
    "flute",
    "fly",
    "forest",
    "fork",
    "france",
    "gas",
    "ghost",
    "giant",
    "glass",
    "glove",
    "gold",
    "grass",
    "greece",
    "green",
    "ham",
    "head",
    "himalaya",
    "hole",
    "hood",
    "hook",
    "human",
    "horseshoe",
    "hospital",
    "hotel",
    "ice",
    "ice cream",
    "india",
    "iron",
    "ivory",
    "jam",
    "jet",
    "jupiter",
    "kangaroo",
    "ketchup",
    "kid",
    "king",
    "kiwi",
    "knife",
    "knight",
    "lab",
    "lap",
    "laser",
    "lawyer",
    "lead",
    "lemon",
    "limousine",
    "leadlock",
    "log",
    "mammoth",
    "maple",
    "march",
    "mass",
    "mercury",
    "millionaire",
    "model",
    "mole",
    "moscow",
    "mouth",
    "mug",
    "needle",
    "net",
    "new york",
    "night",
    "note",
    "novel",
    "nurse",
    "nut",
    "oil",
    "olive",
    "olympus",
    "opera",
    "orange",
    "paper",
    "park",
    "part",
    "paste",
    "phoenix",
    "piano",
    "telescope",
    "teacher",
    "switch",
    "swing",
    "sub",
    "stick",
    "staff",
    "stadium",
    "sprint",
    "spike",
    "snowman",
    "slip",
    "shot",
    "shadow",
    "server",
    "ruler",
    "row",
    "rose",
    "root",
    "rome",
    "rock",
    "robot",
    "robin",
    "revolution",
    "rat",
    "racket",
    "queen",
    "press",
    "port",
    "pilot",
    "time",
    "tooth",
    "tower",
    "truck",
    "triangle",
    "trip",
    "turkey",
    "undertaker",
    "unicorn",
    "vacuum",
    "van",
    "wake",
    "wall",
    "war",
    "washer",
    "washington",
    "water",
    "wave",
    "well",
    "whale",
    "whip",
    "worm",
    "yard"
],
    getRandomWords = () => {
        const s = new Set();
        while (s.size < 25) {
            s.add(words[Math.floor(Math.random() * words.length)]);
        }
        const finalWords = Array.from(s);
        return finalWords;
    },
    getNewLegend = () => {
        //7 nuetral card = 0
        //8 red card = 1
        //8 blue card = 2
        //1 red or blue card = 1 or 2
        //1 assasin card = 3
        var arr = [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 3, Math.floor(Math.random() * (2 - 1 + 1) + 1)];
        for (let i = arr.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [arr[i], arr[j]] = [arr[j], arr[i]];
        }
        return arr;
    };

export { words, getRandomWords, getNewLegend };